version: "3.8"

services:
  go-backend:
    build:
      context: .
      dockerfile: apps/go-backend/Dockerfile.root
    container_name: go-backend
    ports:
      - "8080:8080"

  nest-backend:
    build:
      context: .
      dockerfile: apps/nest-backend/Dockerfile
    container_name: nest-backend
    ports:
      - "3001:3001"

  next-frontend:
    build:
      context: .
      dockerfile: apps/next-frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    container_name: next-frontend
    ports:
      - "3000:3000"
